version: '3.1'
services:
  home:
    container_name: home
    ports:
      - "5000:5000"
    build: ./server-home
    environment:
      REDIS_URL: "redis"
  api:
    container_name: movie.internal-bookingapp.com
    ports:
      - "5000"
    build: ./server-api
    environment:
      REDIS_URL: "redis"
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"